# Generated by Django 2.1.5 on 2019-03-06 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='rented',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Customer.Customer'),
        ),
    ]
