# Generated by Django 2.1.5 on 2019-03-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0003_auto_20190306_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='delete',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
