# Generated by Django 2.1.5 on 2019-03-07 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0004_movies_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='delete',
        ),
    ]
